### ISSUE TITLE
Typo: "Our turquoise <main> section" - main is white

### ISSUE THREAD

**Issue by angineering** [learn-co-curriculum/CSS-Flexbox-Code-Along#4]
This is confusing

**Comment by drakeltheryuujin** [comment]
Hi @angineering,

Good eye, it looks like the CSS was changed in one branch but not another, nor in the README. 
We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
